<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="10" passed="10" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-10-09T10:31:15Z" name="Command line suite" finished-at="2020-10-09T10:31:15Z" duration-ms="762">
    <groups>
    </groups>
    <test started-at="2020-10-09T10:31:15Z" name="Command line test" finished-at="2020-10-09T10:31:15Z" duration-ms="762">
      <class name="com.kount.authnode.KountEventsNodeTest">
        <test-method signature="KountEventsNodeForUserNameNull()[pri:0, instance:com.kount.authnode.KountEventsNodeTest@6025e1b6]" started-at="2020-10-09T10:31:15Z" name="KountEventsNodeForUserNameNull" finished-at="2020-10-09T10:31:15Z" duration-ms="2" status="PASS">
          <exception class="org.forgerock.openam.auth.node.api.NodeProcessException">
            <message>
              <![CDATA[User Name is empty]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.forgerock.openam.auth.node.api.NodeProcessException: User Name is empty
at com.kount.authnode.KountEventsNode.process(KountEventsNode.java:76)
at com.kount.authnode.KountEventsNodeTest.KountEventsNodeForUserNameNull(KountEventsNodeTest.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.forgerock.openam.auth.node.api.NodeProcessException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- KountEventsNodeForUserNameNull -->
      </class> <!-- com.kount.authnode.KountEventsNodeTest -->
      <class name="com.kount.authnode.KountTrustedDeviceNodeTest">
        <test-method signature="KountTrustedDeviceNodeLoginResponseNull()[pri:0, instance:com.kount.authnode.KountTrustedDeviceNodeTest@2d1ef81a]" started-at="2020-10-09T10:31:15Z" name="KountTrustedDeviceNodeLoginResponseNull" finished-at="2020-10-09T10:31:15Z" duration-ms="2" status="PASS">
          <exception class="org.forgerock.openam.auth.node.api.NodeProcessException">
            <message>
              <![CDATA[Kount Login Response is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.forgerock.openam.auth.node.api.NodeProcessException: Kount Login Response is null
at com.kount.authnode.KountTrustedDeviceNode.process(KountTrustedDeviceNode.java:89)
at com.kount.authnode.KountTrustedDeviceNodeTest.KountTrustedDeviceNodeLoginResponseNull(KountTrustedDeviceNodeTest.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.forgerock.openam.auth.node.api.NodeProcessException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- KountTrustedDeviceNodeLoginResponseNull -->
      </class> <!-- com.kount.authnode.KountTrustedDeviceNodeTest -->
      <class name="com.kount.authnode.KountDecisionNodeTest">
        <test-method signature="kountDecisionEmptyResponse()[pri:0, instance:com.kount.authnode.KountDecisionNodeTest@40a4337a]" started-at="2020-10-09T10:31:15Z" name="kountDecisionEmptyResponse" finished-at="2020-10-09T10:31:15Z" duration-ms="160" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kountDecisionEmptyResponse -->
        <test-method signature="kountDecisionForAllow()[pri:0, instance:com.kount.authnode.KountDecisionNodeTest@40a4337a]" started-at="2020-10-09T10:31:15Z" name="kountDecisionForAllow" finished-at="2020-10-09T10:31:15Z" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kountDecisionForAllow -->
        <test-method signature="kountDecisionForChallenge()[pri:0, instance:com.kount.authnode.KountDecisionNodeTest@40a4337a]" started-at="2020-10-09T10:31:15Z" name="kountDecisionForChallenge" finished-at="2020-10-09T10:31:15Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kountDecisionForChallenge -->
        <test-method signature="kountDecisionForLoginResponseNull()[pri:0, instance:com.kount.authnode.KountDecisionNodeTest@40a4337a]" started-at="2020-10-09T10:31:15Z" name="kountDecisionForLoginResponseNull" finished-at="2020-10-09T10:31:15Z" duration-ms="1" status="PASS">
          <exception class="org.forgerock.openam.auth.node.api.NodeProcessException">
            <message>
              <![CDATA[Kount Login Response is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.forgerock.openam.auth.node.api.NodeProcessException: Kount Login Response is null
at com.kount.authnode.KountDecisionNode.process(KountDecisionNode.java:66)
at com.kount.authnode.KountDecisionNodeTest.kountDecisionForLoginResponseNull(KountDecisionNodeTest.java:89)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.forgerock.openam.auth.node.api.NodeProcessException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kountDecisionForLoginResponseNull -->
        <test-method signature="kountDecisionForFailure()[pri:0, instance:com.kount.authnode.KountDecisionNodeTest@40a4337a]" started-at="2020-10-09T10:31:15Z" name="kountDecisionForFailure" finished-at="2020-10-09T10:31:15Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kountDecisionForFailure -->
        <test-method signature="kountDecisionForNotKnowValueResponse()[pri:0, instance:com.kount.authnode.KountDecisionNodeTest@40a4337a]" started-at="2020-10-09T10:31:15Z" name="kountDecisionForNotKnowValueResponse" finished-at="2020-10-09T10:31:15Z" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kountDecisionForNotKnowValueResponse -->
      </class> <!-- com.kount.authnode.KountDecisionNodeTest -->
      <class name="com.kount.authnode.KountLoginNodeTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.kount.authnode.KountLoginNodeTest@22ff4249]" started-at="2020-10-09T10:31:15Z" name="setup" finished-at="2020-10-09T10:31:15Z" duration-ms="543" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="kountLoginForUserNameNull()[pri:0, instance:com.kount.authnode.KountLoginNodeTest@22ff4249]" started-at="2020-10-09T10:31:15Z" name="kountLoginForUserNameNull" finished-at="2020-10-09T10:31:15Z" duration-ms="3" status="PASS">
          <exception class="org.forgerock.openam.auth.node.api.NodeProcessException">
            <message>
              <![CDATA[User Name is empty]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.forgerock.openam.auth.node.api.NodeProcessException: User Name is empty
at com.kount.authnode.KountLoginNode.process(KountLoginNode.java:112)
at com.kount.authnode.KountLoginNodeTest.kountLoginForUserNameNull(KountLoginNodeTest.java:59)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.forgerock.openam.auth.node.api.NodeProcessException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kountLoginForUserNameNull -->
        <test-method signature="kountLoginNodeConfigUSerTypeEmpty()[pri:0, instance:com.kount.authnode.KountLoginNodeTest@22ff4249]" started-at="2020-10-09T10:31:15Z" name="kountLoginNodeConfigUSerTypeEmpty" finished-at="2020-10-09T10:31:15Z" duration-ms="3" status="PASS">
          <exception class="org.forgerock.openam.auth.node.api.NodeProcessException">
            <message>
              <![CDATA[User Type is empty]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.forgerock.openam.auth.node.api.NodeProcessException: User Type is empty
at com.kount.authnode.KountLoginNode.getKountLoginRequest(KountLoginNode.java:123)
at com.kount.authnode.KountLoginNodeTest.kountLoginNodeConfigUSerTypeEmpty(KountLoginNodeTest.java:70)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- org.forgerock.openam.auth.node.api.NodeProcessException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- kountLoginNodeConfigUSerTypeEmpty -->
        <test-method is-config="true" signature="setup()[pri:0, instance:com.kount.authnode.KountLoginNodeTest@22ff4249]" started-at="2020-10-09T10:31:15Z" name="setup" finished-at="2020-10-09T10:31:15Z" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
      </class> <!-- com.kount.authnode.KountLoginNodeTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
